### ISSUE TITLE
when u making readme

### ISSUE THREAD

**Issue by WhundAlt** [Erder00/royale-brawl-v29#1]
sorry to bother but when are u making the docs? if you need just take your time but can you give me an estimated date? ive been trying but im getting auth error so idk

**Comment by Erder00** [comment]
not sure, just follow the readme for royale brawl v27 for now. it's basically the same

**Comment by WhundAlt** [comment]
i get this error: 


Unhandled exception. MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host '127.0.0.1' for user 'root' using method 'mysql_native_password' failed with message: Access denied for user 'root'@'localhost' (using password: YES)
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'root'@'localhost' (using password: YES)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Supercell.Laser.Server.Database.Accounts.GetMaxAvatarId() in C:\Users\ASUS\Downloads\royale-brawl-v29-main\royale-brawl-v29-main\src\Supercell.Laser.Server\Database\Accounts.cs:line 48
   at Supercell.Laser.Server.Database.Accounts.Init(String user, String password) in C:\Users\ASUS\Downloads\royale-brawl-v29-main\royale-brawl-v29-main\src\Supercell.Laser.Server\Database\Accounts.cs:line 42
   at Supercell.Laser.Server.Resources.InitDatabase() in C:\Users\ASUS\Downloads\royale-brawl-v29-main\royale-brawl-v29-main\src\Supercell.Laser.Server\Resources.cs:line 20
   at Supercell.Laser.Server.Program.Main(String[] args) in C:\Users\ASUS\Downloads\royale-brawl-v29-main\royale-brawl-v29-main\src\Supercell.Laser.Server\Program.cs:line 30

any idea why?

**Comment by Erder00** [comment]
Set mysql credentials in config.json

**Comment by WhundAlt** [comment]
i did put them but it gives error (that error doesnt happen with normal royale brawl v27), is there something wrong in the script?

**Comment by Erder00** [comment]
No

**Comment by Erder00** [comment]
Oh, I think I know why. The credentials are hard coded, it doesn't fully respect the config file yet

**Comment by WhundAlt** [comment]
i already fixed it, yea the database/accounts and alliances.cs were with the password "erder" so its fixed

**Comment by Erder00** [comment]
keeping this open to remind myself to fix config mess

**Comment by Erder00** [comment]
okay, fixed

**Comment by WhundAlt** [comment]
quick question: no pvp battles (online) or just wip??

**Comment by Erder00** [comment]
No and I probably won't do online battles for now
